model_provider = "aicodemirror"
model = "gpt-5.4"
model_reasoning_effort = "xhigh"
plan_mode_reasoning_effort = "xhigh"
disable_response_storage = true
preferred_auth_method = "apikey"
approvals_reviewer = "guardian_subagent"
approval_policy = "on-request"
sandbox_mode = "danger-full-access"
service_tier = "fast"

[model_providers.aicodemirror]
name = "aicodemirror"
base_url = "https://api.aicodemirror.com/api/codex/backend-api/codex"
wire_api = "responses"

[features]
multi_agent = true
guardian_approval = true
js_repl = true

[notice]
hide_full_access_warning = true

[tui]
status_line = ["model-with-reasoning", "current-dir", "git-branch", "context-remaining", "total-input-tokens", "total-output-tokens", "fast-mode"]

[[skills.config]]
path = "/root/.codex/skills/.system/openai-docs/SKILL.md"
enabled = false


[projects."/root/.claude"]
trust_level = "trusted"
[projects."/root/.codex"]
trust_level = "trusted"
[projects."/root/.conan"]
trust_level = "trusted"
[projects."/root/.conan2"]
trust_level = "trusted"
[projects."/root/.config/emacs"]
trust_level = "trusted"
[projects."/root/.config/git"]
trust_level = "trusted"
[projects."/root/.config/pip"]
trust_level = "trusted"
[projects."/root/.copilot"]
trust_level = "trusted"
[projects."/root/.gemini"]
trust_level = "trusted"
[projects."/root/.github"]
trust_level = "trusted"
[projects."/root/.github/workflows"]
trust_level = "trusted"
[projects."/root/.vscode"]
trust_level = "trusted"
[projects."/root/Documents/PowerShell"]
trust_level = "trusted"
[projects."/root/Music"]
trust_level = "trusted"
