default_model = "百炼/kimi-k3"
default_permission_mode = "auto"
telemetry = false

[thinking]
enabled = true
keep = "all"



[providers.百炼]
type = "openai"
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"

[providers.仙工-openai]
type = "openai"
base_url = "https://vibeg.seer-robotics.cn/openai/v1"



[models."百炼/kimi-k3"]
provider = "百炼"
model = "kimi-k3"
max_context_size = 1048576
capabilities = [ "image_in", "thinking", "tool_use", "always_thinking" ]
display_name = "Kimi K3"
reasoning_key = "reasoning_content"
support_efforts = [ "max" ]
default_effort = "max"

[models."百炼/qwen3.8-max"]
provider = "百炼"
model = "qwen3.8-max"
max_context_size = 1000000
capabilities = [ "image_in", "video_in", "thinking", "tool_use", "always_thinking" ]
display_name = "Qwen3.8 Max"
reasoning_key = "reasoning_content"

[models."百炼/glm-5.3"]
provider = "百炼"
model = "glm-5.3"
max_context_size = 1000000
capabilities = [ "thinking", "tool_use", "always_thinking" ]
display_name = "GLM-5.3"
reasoning_key = "reasoning_content"
support_efforts = [ "max" ]
default_effort = "max"
