default_model = "alibaba-cn/kimi-k3"
default_permission_mode = "auto"
telemetry = false

[thinking]
enabled = true
keep = "all"





[providers.alibaba-cn]
type = "openai"
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"

[providers.seer-openai]
type = "openai"
base_url = "https://vibeg.seer-robotics.cn/openai/v1"





[models."alibaba-cn/kimi-k3"]
provider = "alibaba-cn"
model = "kimi/kimi-k3"
max_context_size = 1048576
capabilities = [ "thinking", "always_thinking", "image_in", "video_in", "tool_use" ]
display_name = "K3"
support_efforts = [ "low", "high", "max" ]
default_effort = "max"

[models."alibaba-cn/qwen3.8-max"]
provider = "alibaba-cn"
model = "qwen3.8-max"
max_context_size = 1000000
capabilities = [ "image_in", "video_in", "thinking", "tool_use" ]
display_name = "Qwen3.8 Max"
reasoning_key = "reasoning_content"
support_efforts = [ "low", "medium", "xhigh" ]
default_effort = "xhigh"

[models."seer-openai/glm-5.3"]
provider = "seer-openai"
model = "glm-5.3"
max_context_size = 1000000
capabilities = [ "always_thinking", "tool_use" ]
display_name = "GLM-5.3"
reasoning_key = "reasoning_content"
support_efforts = [ "low", "high", "max" ]
default_effort = "max"

[models."seer-openai/glm-5.3-flash"]
provider = "seer-openai"
model = "glm-5.3-flash"
max_context_size = 1000000
capabilities = [ "image_in", "video_in", "always_thinking", "tool_use" ]
display_name = "GLM-5.3-Flash"
reasoning_key = "reasoning_content"
support_efforts = [ "low", "high", "max" ]
default_effort = "max"
