name: Update Submodule .emacs.d

on:
  # run automatically
  schedule:
    - cron: "0 0 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: first step
        run: |
          git submodule update --init '.emacs.d'
          git add '.emacs.d'
          git commit -m '[action]Update Submodule .emacs.d'
