name: Auto chmod +x .local/bin/*
on:
  push:
    paths:
      - '.local/bin/*'
permissions:
  contents: write
jobs:
  chmod+x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false
      - name: chmod +x
        run: chmod +x .local/bin/*
      - name: Commit & Push
        run: |
          git diff --quiet && exit
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .local/bin/
          git commit -m '; chore: chmod +x .local/bin/*'
          git push
