name: Update Submodule .emacs.d
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-config-emacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1
      - name: Update _emacs from Upstream
        run: |
          git submodule update --init --depth=1 -- .config/emacs
          cd .config/emacs
          git fetch --depth=1 origin trunk
          git checkout FETCH_HEAD
      - name: Commit & Push if Changed
        run: |
          if git diff --quiet -- .config/emacs; then
            echo '_emacs is already up to date'
            exit
          fi
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .config/emacs
          git commit -m '; chore: update submodule .config/emacs'
          git push origin HEAD:${{ github.ref_name }}
